#!/usr/bin/expect

spawn ./console-setup.sh
expect "Java Home"
send "\r"
expect "iDempiere Home"
send "\r"
expect "Key Store Password"
send "idempiere\n"
expect "Common Name"
send "idempiere\r"
expect "Organization Unit"
send "RnD\r"
expect "Organization"
send "NA\r"
expect "Locale/Town"
send "Tokyo\r"
expect "State"
send "\r"
expect "Country"
send "JP\r"
expect "Application Server Host Name"
send "\r"
expect "Application Server Web Port"
send "\r"
expect "Application Server SSL Port"
send "\r"
expect "DB Already Exists"
send "\r"
expect "Database Type"
send "2\r"
expect "Database Server Host Name"
send "127.0.0.1\r"
expect "Database Server Port"
send "\r"
expect "Database Name"
send "\r"
expect "Database user"
send "\r"
expect "Database Password"
send "\r"
expect "Database System User Password"
send "postgres\r"
expect "Mail Server Host Name"
send "smtp.gmail.com\r"
expect "Mail User Login"
send "reoring@gmail.com\r"
expect "Mail User Password"
send "kuso1228\r"
expect "Administrator EMail"
send "idempiere@example.com\r"
expect "Save changes"
send "Y\r"
expect eof
